image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip --version
  - pip install --upgrade pip
  - pip install virtualenv
  - test -d venv || virtualenv venv
  - source venv/bin/activate
  - pip install build
run:
  script:
    - pip install .
    - cd gumicorn
    - python -m build
  artifacts:
    paths:
      - build/*