#!/bin/sh

GUMICORN=/usr/local/bin/gumicorn
ROOT=/path/to/project
PID=/var/run/gumicorn.pid

APP=main:application

if [ -f $PID ]; then rm $PID; fi

cd $ROOT
exec $GUMICORN -c $ROOT/gumicorn.conf.py --pid=$PID $APP
